---
title: "fecundity test"
output: html_document
---

```{r cars}
library(ggplot2)
library(dplyr)

ggplot(Fecundity, aes(x = species)) + 
  geom_bar() +
  theme_minimal(base_size = 12)

Fecundity <- Fecundity %>% filter(count !="NA") %>% transform(count = as.numeric(count)) 
Fecundity1 <- Fecundity %>% select(species, count)
acwr <- Fecundity %>% filter(species == "AC", count !="NA")
brma <- Fecundity %>% filter(species == "BR", count !="NA")
homu <- Fecundity %>% filter(species == "HO", count !="NA")
femi <- Fecundity %>% filter(species == "FE", count !="NA")
laca <- Fecundity %>% filter(species == "LA", count !="NA")
naat <- Fecundity %>% filter(species == "NA", count !="NA")
pler <- Fecundity %>% filter(species == "PL", count !="NA")
saco <- Fecundity %>% filter(species == "SA", count !="NA")
urli <- Fecundity %>% filter(species == "UR", count !="NA")

summary(acwr$count) 
quantile(acwr$count, prob=c(.25,.5,.75), na.rm=TRUE)

Fecundity1 %>% group_by(species) %>% summarise(avg = mean(count), min = min(count), max=max(count))

df <- data.frame(species = c("AC","BR","HO","FE","LA","PL","SA","UR"),
  Var= c(var(acwr$count), var(brma$count),var(homu$count),var(femi$count),var(laca$count),var(pler$count),var(saco$count),var(urli$count)),
  SD= c(sd(acwr$count), sd(brma$count),sd(homu$count),sd(femi$count),sd(laca$count),sd(pler$count),sd(saco$count),sd(urli$count))
)
df

```

```{r}
Fecundity2 <- Fecundity1 %>% filter(species %in% c("AC", "HO", "PL", "SA", "UR"))
Fecundity3 <- Fecundity1 %>% filter(species %in% c("BR", "FE", "LA"))
ggplot(Fecundity1, aes(x=species, y=count, fill=species)) + geom_boxplot() + coord_flip() + theme_minimal()

```
