
```{r}
install.packages("PressPurt")
devtools::install_github("mikeyEcology/MLWIC2")
library(MLWIC2)
MLWIC2::runShiny('setup')

MLWIC2::setup(python_loc = "/opt/anaconda3/bin/python3",gpu = FALSE)

#r-reticulate=FALSE
options(timeout=600)
#/Users/hayleeoyler/Library/r-miniconda

find_python()
#environment location: /Users/hayleeoyler/.conda/environments.txt

create_conda_env(condaenv="PressPurtEnv", 
                  version="/opt/anaconda3/bin/python3", 
                  verbose = TRUE)

py_depend(condaenv = "PressPurtEnv")
set_python_conda(condaenv="PressPurtEnv")

input_file(data_info.csv)
make_input(data_info.csv)
MLWIC2::runShiny('make_input')
getwd()
setwd("/Users/hayleeoyler/Desktop/MLWIC_examples-master")
classify(path_prefix = "/Users/hayleeoyler/Desktop/MLWIC_examples-master/images", # this is the absolute path to the images. 
         data_info = "/Users/hayleeoyler/Desktop/MLWIC_examples-master/image_labels.csv", # this is the location of the csv containing image information. It has Unix linebreaks and no headers.
         model_dir = "/Users/hayleeoyler/Desktop/MLWIC_examples-master", # assuming this is where you stored the L1 folder in Step 3 of the instructions: github.com/mikeyEcology/MLWIC/blob/master/README
         python_loc = "/opt/anaconda3/bin", # the location of Python on your computer. 
         save_predictions = "model_predictions.txt" # this is the default and you should use it unless you have reason otherwise.
         )
```

```{r}
library(devtools) # load package
devtools::install_github("r-lib/pkgbuild") # install updated version of pkgbuild from GitHub
library(pkgbuild) # load package
find_rtools() # should be TRUE, assuming you have Rtools 3.5
```

